url: https://y7kim.github.io
baseurl: ""

# Site settings
title: Whissol
email: info@whissol.com
description: ""


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: google-play
      url: #
    - title: app-store
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames
social:
  - title: twitter
    url:
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty