url: https://dbbill.github.io
baseurl: ""

# Site settings
title: Whissol
email: info@whissol.com
description: ""

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/whissol_
  - title: facebook
    url: #

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: assets/css
