repository                                : dbbill/dbbill.github.io
page_title                                : Whissol
body_background_color                     : "#ffffff"

# App Info

app_icon                                  : assets/images/icon.png
app_name                                  : Whissol
app_price                                 : Free
app_description                           : Play against your friends in sports knockout tournaments

appstore_link                             : L
playstore_link                            : L

device_color                              : blue

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"
coming_soon_color                         : "#04113b"

# Description

description: >
  Whissol is a fun and easy way to compete against your friends in "last man standing" style tournaments. 
  We've given you complete control so that you can run every tournament in a way that suits your group of friends. 
  It's incredibly simple to play and manage!

# Features

features                                  :

  - title                                 : Groups
    description                           : >
      Create a group and invite your friends to join by giving them the access code.
    fontawesome_icon_name                 : user-group

  - title                                 : Simple
    description                           : >
      Tournaments are incredibly easy to create and manage. We'll take care of all the hard bits.
    fontawesome_icon_name                 : trophy

  - title                                 : Automatic Results
    description                           : >
      We'll automatically update results and manage who has been eliminated from a tournament.
    fontawesome_icon_name                 : sync

  - title                                 : Choose Days
    description                           : >
      Decide when a round takes place. 
      Select the days that you'd like to include and only fixtures taking place on those days will be added to the round.
    fontawesome_icon_name                 : calendar-days

  - title                                 : Choose Leagues
    description                           : >
      Choose which leagues players can pick a team from. 
      Simply select the leagues that you'd like to include and only fixtures from those leagues will be added to the round.
    fontawesome_icon_name                 : list

  - title                                 : Multiple Leagues
    description                           : >
      We've included leagues and competitions from around the world. Let us know if you'd like us to add another.
    fontawesome_icon_name                 : globe
  
  - title                                 : Multiple Sports (Coming Soon)
    description                           : >
      We'll be including more sports in future versions. Let us know if there is a particular sport you'd like to see included.
    fontawesome_icon_name                 : layer-group

  - title                                 : Push Notifications (Coming Soon)
    description                           : >
      We'll send you updates and reminders via push notifications (you'll be able to turn these off in your settings).
    fontawesome_icon_name                 : bell

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffd500"
feature_icons_background_color            : "#04113b"

# Rules

rules_summary                             : Players must pick a team in each round until they are eliminated
rules                                     :

  - title                                 : Eliminated?
    description                           : A player will be eliminated from a tournament when one of their picked teams loses or draws.
    fontawesome_icon_name                 : close
  - title                                 : Winner?
    description                           : A tournament ends when, at the end of a round, all but one player has been eliminated or if all players have been eliminated.
    fontawesome_icon_name                 : trophy
  - title                                 : Bye
    description                           : If a fixture is postponed, abandoned, or cancelled, any player that picked one of the teams in that fixture will be given a bye and must pick two teams in the next round.
    fontawesome_icon_name                 : arrow-right
  - title                                 : No Repeat Picks
    description                           : A player cannot choose the same team twice in a tournament.
    fontawesome_icon_name                 : repeat
  - title                                 : Pick Deadline
    description                           : Players must pick their teams before the first kick off of the round.
    fontawesome_icon_name                 : hourglass-end
  - title                                 : Unmade Picks
    description                           : A player will be eliminated from the tournament if they forget to pick a team in a round.
    fontawesome_icon_name                 : circle
  - title                                 : Changing Your Pick
    description                           : A player can change the team they have picked at any time before a round starts.
    fontawesome_icon_name                 : right-left
  - title                                 : Other Players
    description                           : You'll only be able to see which teams other players have picked once the round starts.
    fontawesome_icon_name                 : eye

rule_icons_foreground_color            : "#ffffff"
rule_icons_background_color            : "#00c853ff"

# Socials

email_address                             : info@whissol.com
facebook_username                         : whissol
twitter_username                          : whissol_

social_icons_foreground_color             : "#ffd500"
social_icons_background_color             : "#04113b"

# Footer

footer_text_color                         : "#666666"
link_color                                : "#1d63ea"

# Build

collections:
  pages:
    output: true
    permalink: /:path

markdown: kramdown
sass:
  style: compressed
